### PR TITLE
Start investigating intel failure in more detail

### LINKED ISSUE #113: Test failures with new Intel compiler
We have some persistent and strange test failures with the new Intel compiler.

See, e.g. https://github.com/Chaste/Chaste/actions/runs/5310621344/jobs/9612829772

```
The following tests FAILED:
	 15 - TestFloatingPointDivisionByZero (Failed)
	 16 - TestFloatingPointDivisionByZeroPetsc (Failed)
	 21 - TestMathsCustomFunctions (Failed)
	237 - TestCellPopulationWriters (Failed)
	262 - TestOffLatticeSimulation (Failed)
	327 - TestCryptProjectionStatistics (Failed)
	346 - TestAirwayRemesher (Subprocess aborted)
	380 - TestDynamicallyLoadedCellModels (Failed)
	418 - TestPlaneStimulusCellFactory (Failed)
```

These failures include very strange failures such as:

```
Entering TestSmallPowFloatingPoint

.../TestMathsCustomFunctions.hpp:65: Error: Expected (SmallPow(75.0, i) == std::pow(75.0, i)) up to 1e-12 (0.0000), found (5625.0000 != 5624.9999)
.../TestMathsCustomFunctions.hpp:65: Error: Expected (SmallPow(75.0, i) == std::pow(75.0, i)) up to 1e-12 (0.0000), found (421875.0000 != 421874.9999)
.../TestMathsCustomFunctions.hpp:65: Error: Expected (SmallPow(75.0, i) == std::pow(75.0, i)) up to 1e-12 (0.0000), found (31640625.0088 != 31640624.9988)
.../TestMathsCustomFunctions.hpp:65: Error: Expected (SmallPow(75.0, i) == std::pow(75.0, i)) up to 1e-12 (0.0000), found (2373046875.8888 != 2373046874.8888)
```

This is strange because, while it looks as though it might be a precision issue, note that the last one is off by a whole 1.0, which is not simply a lack of precision in intermediate calculations...

## Reproducing these errors

I can't reproduce these errors.

I have tried locally, and the whole test suite passes.
I have tried the small pow test on the [Compiler Explorer](https://gcc.godbolt.org/) and can't reproduce it there, either.

## Investigation

I have created a branch and associated draft PR: #112

### PR DESCRIPTION
**Pull request by fcooper8472**
This branch is just for investigating the intel failure.

See, e.g. https://github.com/Chaste/Chaste/actions/runs/5310621344/jobs/9612829772

```
The following tests FAILED:
	 15 - TestFloatingPointDivisionByZero (Failed)
	 16 - TestFloatingPointDivisionByZeroPetsc (Failed)
	 21 - TestMathsCustomFunctions (Failed)
	237 - TestCellPopulationWriters (Failed)
	262 - TestOffLatticeSimulation (Failed)
	327 - TestCryptProjectionStatistics (Failed)
	346 - TestAirwayRemesher (Subprocess aborted)
	380 - TestDynamicallyLoadedCellModels (Failed)
	418 - TestPlaneStimulusCellFactory (Failed)
```

### CODE REVIEW

File: global/test/TestTimer.hpp [hunk 1]
```diff
@@ -60,11 +62,15 @@ class TestTimer : public CxxTest::TestSuite
...
-        for (unsigned i=2; i<1000; )
+        // Small amount of work in a loop that can't be optimized by unrolling.
+        // Updated 2023-06-20 to make it even less likely the compiler will optimize this work away.
+        volatile double number = 0.0;
+        for (unsigned i = 1; i < 10'000; ++i)
         {
-            i += (int) floor(sqrt(i));
+            number += std::asinh(0.001 * i);
         }
+        TS_ASSERT_LESS_THAN(20'930.0, number);
```
Comment (mirams) [inline global/test/TestTimer.hpp:72]: typo?

Comment (fcooper8472) [reply global/test/TestTimer.hpp:72]: If you're referring to the `20'930.0`, then no, this is legal since C++14:
https://en.cppreference.com/w/cpp/language/floating_literal

The compiler completely ignores it, but you can use it like you would use a comma to aid readability for long numbers.

**Comment by fcooper8472** [comment]
Main changes in the PR:

- Turn on `-fp-model precise` by default when using the Intel compiler: this makes it behave much more in line with our expectations regarding NaN, INF etc
- Users can disable this (and get the default fast floating point mode) using the new option `Chaste_USE_INTEL_PRECISE_FP_MODEL`
- Added the ChasteTestOutput directory to ChasteTestBuildInfo. This is just something useful that would have saved me some time while developing!
- Modified the "work" being done in TestTimer to make it much less likely the compiler will optimize it away
- Ensure the dynamic models in heart are built with the individual unit tests that need them
- Revert the behaviour of TestMonodomainWithSvi, now that we have fixed Intel to the precise model
